version: "3"
services:
  bot:
    container_name: "bot"
    depends_on:
      - "mysql"
    build: ./docker
    ports:
      - 8080:8080
    volumes:
      - ./:/var/opt/bot
      - "${HOME}/.m2:/root/.m2"
    environment:
      - DB_HOST=bot-mysql
      - BOT_TOKEN=/var/opt/bot/bot-token.txt
  mysql:
    container_name: "bot-mysql"
    image: mariadb:10.1.48
    ports:
      - 33060:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bot
      - MYSQL_USER=bot
      - MYSQL_PASSWORD=bot