name: build-docker-and-publish

on:
  release:
    types: [ released ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
      attestations: write

    steps:
    - uses: actions/checkout@v4
      name: Check out code

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          docker.io/brandonfl/discord-role-persistence
          ghcr.io/brandonfl/discord-role-persistence/discord-role-persistence
        tags: |
          type=semver,pattern={{version}},prefix=v
          type=raw,value=latest,enable=true
        labels: |
          org.opencontainers.image.title=Discord Role Persistence
          org.opencontainers.image.description=Discord Role Persistence is a verified Discord bot with the objective to save the roles of users even after a leave/join server.
          org.opencontainers.image.url=https://discord-role-persistence.com
          org.opencontainers.image.authors=Brandon Fontany--Legall <brandon@fontany-legall.xyz>
          org.opencontainers.image.licenses=MIT

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      id: push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        provenance: ${{ vars.DOCKER_BUILD_PROVENANCE }}
        sbom: ${{ vars.DOCKER_BUILD_SBOM }}

    - name: Attest Docker image on Docker Hub
      uses: actions/attest-build-provenance@v1.2.0
      with:
        subject-name: docker.io/brandonfl/discord-role-persistence
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true

    - name: Attest Docker image on GitHub Container Registry
      uses: actions/attest-build-provenance@v1.2.0
      with:
        subject-name: ghcr.io/brandonfl/discord-role-persistence/discord-role-persistence
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true

    - name: Discord message notification
      uses: appleboy/discord-action@v1.0.0
      continue-on-error: true
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        message: 'New <@&760194811356643348> of Discord Role Persistence has been released with version ${{ github.ref_name }} :partying_face:'
