name: build-docker-and-publish

on:
  release:
    types: [ released ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out code
      
    - uses: docker/build-push-action@v1.1.0
      name: Build & push Docker image on Github
      with:
        tags: latest
        tag_with_ref: true
        registry: docker.pkg.github.com
        repository: brandonfl/discord-role-persistence/discord-role-persistence
        dockerfile: Dockerfile
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/build-push-action@v1.1.0
      name: Build & push Docker image on Dockerhub
      with:
        tags: latest
        tag_with_ref: true
        repository: brandonfl/discord-role-persistence
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
